allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  bcrypt: true
  core-js: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
