import { auth } from "@/auth";
import db from "@/lib/db";
import { buildEnglishTranslationPayload, prismaUniqueMessage } from "@/lib/i18n/translationPayload";
import { safelyEnqueueTranslationJobs } from "@/lib/queues/safe-translation-enqueue";
import { createTranslationSourceHash } from "@/lib/translations/source-hash";
import { NextResponse } from "next/server";
import { assertAdmin } from "@/lib/security"; const hsnCodeSelect = { id: true, code: true, description: true, gstRate: true, cgstRate: true, sgstRate: true, igstRate: true, cessRate: true, taxType: true, chapter: true, effectiveTo: true,
};
export async function POST(request) { try { const session = await auth(); const denied = assertAdmin(session); if (denied) return denied; const { title, slug, imageUrl, description, hsnCodeId, isActive } = await request.json(); const englishTranslation = buildEnglishTranslationPayload({ title, slug, description, }); const sourceHash = createTranslationSourceHash(englishTranslation); const resolvedHsnCodeId = hsnCodeId || null; const hsnCode = resolvedHsnCodeId ? await db.hsnCode.findFirst({ where: { id: resolvedHsnCodeId, status: "ACTIVE", OR: [{ effectiveTo: null }, { effectiveTo: { gte: new Date() } }], }, select: { id: true }, }) : null; if (resolvedHsnCodeId && !hsnCode) { return NextResponse.json({ message: "Selected HSN code is invalid, inactive, or expired" }, { status: 400 }); } const existingCategory = await db.category.findUnique({ where: { slug, }, }); if (existingCategory) { return NextResponse.json( { data: null, message: `Category ( ${title}) already exists in the Database`, }, { status: 409 } ); } const newCategory = await db.category.create({ data: { title, slug, imageUrl, description, hsnCodeId: resolvedHsnCodeId, isActive, translations: { create: { language: englishTranslation.language, title: englishTranslation.title, slug: englishTranslation.slug, description: englishTranslation.description, metaTitle: englishTranslation.metaTitle, metaDescription: englishTranslation.metaDescription, }, }, }, include: { translations: true, hsnCode: { select: hsnCodeSelect, }, }, }); await safelyEnqueueTranslationJobs({ entityType: "CATEGORY", entityId: newCategory.id, sourceHash, }); return NextResponse.json(newCategory); } catch (error) { console.error(error); return NextResponse.json( { message: prismaUniqueMessage(error, "Failed to create Category"), error, }, { status: 500 } ); }
}
export async function GET(request) { try { const categories = await db.category.findMany({ orderBy: { createdAt: "desc", }, include: { products: true, subCategories: true, translations: true, hsnCode: { select: hsnCodeSelect, }, }, }); return NextResponse.json(categories); } catch (error) { console.error(error); return NextResponse.json( { message: "Failed to Fetch Category", error, }, { status: 500 } ); }
}
