import { auth } from "@/auth";
import { writeAiAuditLog } from "@/lib/ai/audit-log";
import { generateAiResponse } from "@/lib/ai/provider";
import { PRODUCT_GENERATION_PROMPT } from "@/lib/ai/prompts";
import { checkAiRateLimit } from "@/lib/ai/rate-limit";
import { assertSafeUserPrompt, hashAiInput } from "@/lib/ai/safety";
import { aiProductGeneratedDraftSchema, productGenerationSchema } from "@/lib/ai/validators";
import db from "@/lib/db";
import { forbidden, rateLimited, unauthorized } from "@/lib/security";
import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server"; function parseGeneratedJson(content: string) {
    try { const parsed = JSON.parse(content) as Record<string, unknown>; const draft = aiProductGeneratedDraftSchema.safeParse(parsed); return draft.success ? draft.data : null; } catch { return null; }
}
function fallbackDraft(input: { productName: string; brand?: string; language?: string }) {
    const title = input.brand ? `${input.brand} ${input.productName}` : input.productName; return { title, shortDescription: `${title} for Nxbazaar.in customers.`, detailedDescription: `${title} listing draft. Review all specifications, price, stock, warranty, GST and HSN details before publishing.`, features: ["Review product material", "Add accurate size and colour", "Confirm stock and pricing"], seoTitle: title, metaDescription: `Shop ${title} on Nxbazaar.in.`, keywords: [input.productName, input.brand].filter(Boolean), translations: { hi: { title, shortDescription: "" }, mr: { title, shortDescription: "" }, }, hsnReviewRequired: true, };
}
async function saveGenerationDraft(input: {
    userId?: string; userRole?: string; inputHash: string; generatedJson: Record<string, unknown>;
}) {
    await db.$executeRaw` INSERT INTO "AiGeneration" ("id", "userId", "userRole", "feature", "entityType", "status", "inputHash", "generatedJson", "createdAt", "updatedAt") VALUES (${randomUUID()}, ${input.userId ?? null}, ${input.userRole ?? null}, 'product_generation', 'Product', 'DRAFT', ${input.inputHash}, ${JSON.stringify(input.generatedJson)}::jsonb, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) `;
}
export async function POST(request: Request) {
    const startedAt = Date.now(); const session = await auth(); if (!session?.user?.id) return unauthorized(); if (!["ADMIN", "MODERATOR", "SELLER", "FARMER"].includes(String(session.user.role))) return forbidden(); const parsed = productGenerationSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) { return NextResponse.json({ message: "Invalid product generation request" }, { status: 400 }); } const promptText = JSON.stringify(parsed.data); const safety = assertSafeUserPrompt(promptText); if (!safety.ok) return NextResponse.json({ message: safety.message }, { status: 400 }); const rateLimit = checkAiRateLimit(session.user.id, "product_generation"); if (rateLimit.ok === false) return rateLimited(rateLimit.retryAfterMs); const [categories, subCategories] = await Promise.all([db.category.findMany({ where: { isActive: true }, select: { id: true, title: true, hsnCodeId: true }, take: 100 }), db.subCategory.findMany({ where: { isActive: true }, select: { id: true, title: true, categoryId: true, hsnCodeId: true }, take: 200 }),]); let draft = aiProductGeneratedDraftSchema.parse(fallbackDraft(parsed.data)); let aiStatus: "success" | "fallback" = "fallback"; try { const ai = await generateAiResponse({ feature: "product_generation", messages: [{ role: "system", content: PRODUCT_GENERATION_PROMPT }, { role: "user", content: JSON.stringify({ productInput: parsed.data, existingCategories: categories, existingSubCategories: subCategories, requiredJsonKeys: ["title", "shortDescription", "detailedDescription", "features", "seoTitle", "metaDescription", "keywords", "translations", "categoryId", "subCategoryId", "attributeSuggestions", "hsnReviewRequired",], }), },], responseFormat: "json", maxTokens: 1_200, temperature: 0.3, }); draft = parseGeneratedJson(ai.content) ?? draft; aiStatus = "success"; await writeAiAuditLog({ feature: "product_generation", status: "success", userId: session.user.id, userRole: session.user.role, requestHash: hashAiInput(promptText), promptTokens: ai.usage?.promptTokens, outputTokens: ai.usage?.outputTokens, latencyMs: Date.now() - startedAt, metadata: { provider: ai.provider, model: ai.model }, }); } catch (error) { await writeAiAuditLog({ feature: "product_generation", status: "error", userId: session.user.id, userRole: session.user.role, requestHash: hashAiInput(promptText), latencyMs: Date.now() - startedAt, errorMessage: error instanceof Error ? error.message : "AI generation failed", }).catch(() => undefined); } await saveGenerationDraft({ userId: session.user.id, userRole: session.user.role, inputHash: hashAiInput(promptText), generatedJson: draft, }).catch(() => undefined); return NextResponse.json({ draft, aiStatus, message: "AI draft generated for preview. Nothing was saved to the product record.", });
}
