import { auth } from "@/auth";
import db from "@/lib/db";
import { NextResponse } from "next/server";
import { assertAuthenticated, forbidden, isAdmin } from "@/lib/security";
export async function GET(request: Request, context: { params: Promise<{ id: string }> }) { const { id } = await context.params; try { const coupon = await db.coupon.findUnique({ where: { id, }, }); return NextResponse.json(coupon); } catch (error) { console.error(error); return NextResponse.json( { message: "Failed to Fetch Coupon", error, }, { status: 500 } ); }
}
export async function DELETE(request: Request, context: { params: Promise<{ id: string }> }) { const { id } = await context.params; try { const session = await auth(); const denied = assertAuthenticated(session); if (denied) return denied; const existingCoupon = await db.coupon.findUnique({ where: { id, }, }); if (!existingCoupon) { return NextResponse.json( { data: null, message: "Coupon Not Found", }, { status: 404 } ); } if (!isAdmin(session) && existingCoupon.vendorId !== session.user.id) { return forbidden(); } const deletedCoupon = await db.coupon.delete({ where: { id, }, }); return NextResponse.json(deletedCoupon); } catch (error) { console.error(error); return NextResponse.json( { message: "Failed to Delete Coupon", error, }, { status: 500 } ); }
}
export async function PUT(request: Request, context: { params: Promise<{ id: string }> }) { const { id } = await context.params; try { const session = await auth(); const denied = assertAuthenticated(session); if (denied) return denied; const { title, couponCode, expiryDate, isActive } = await request.json(); const existingCoupon = await db.coupon.findUnique({ where: { id, }, }); if (!existingCoupon) { return NextResponse.json( { data: null, message: `Not Found`, }, { status: 404 } ); } if (!isAdmin(session) && existingCoupon.vendorId !== session.user.id) { return forbidden(); } const updatedCoupon = await db.coupon.update({ where: { id }, data: { title, couponCode, expiryDate, isActive, }, }); return NextResponse.json(updatedCoupon); } catch (error) { console.error(error); return NextResponse.json( { message: "Failed to Update Coupon", error, }, { status: 500 } ); }
}
