"use client";
import { searchHsnCodes } from "@/actions/hsn-code";
import { X } from "lucide-react";
import { useEffect, useMemo, useState, useTransition } from "react"; type RateLike = number | { toString(): string };
export type HsnOption = { id: string; code: string; description: string; gstRate: RateLike; cgstRate: RateLike; sgstRate: RateLike; igstRate: RateLike; cessRate: RateLike; status?: string; chapter?: string | null;
};
export default function HsnCodeSelector({ value, onChange, initialOption, placeholder = "Search HSN code", disabled = false,
}: { value?: string; onChange: (value: string | null, option?: HsnOption | null) => void; initialOption?: HsnOption | null; placeholder?: string; disabled?: boolean;
}) { const [query, setQuery] = useState(initialOption ? `${initialOption.code} - ${initialOption.description}` : ""); const [results, setResults] = useState<HsnOption[]>([]); const [selected, setSelected] = useState<HsnOption | null>(initialOption ?? null); const [isOpen, setIsOpen] = useState(false); const [isPending, startTransition] = useTransition(); useEffect(() => { if (!isOpen) { return; } const handle = window.setTimeout(() => { startTransition(async () => {
const search = selected?.id === value ? "" : query.trim(); if (search.length === 1) { setResults([]); return; } const response = await searchHsnCodes(search); setResults(response.success ? (response.data as HsnOption[]) : []); }); }, 300); return () => window.clearTimeout(handle); }, [isOpen, query, selected?.id, value]); const selectedSummary = useMemo(() => { if (!selected) return null; return `GST: ${selected.gstRate}% | CGST: ${selected.cgstRate}% | SGST: ${selected.sgstRate}% | IGST: ${selected.igstRate}%`; }, [selected]); return ( <div className="relative space-y-2"> <div className="flex gap-2"> <input value={query} onFocus={() => setIsOpen(true)} onBlur={() => { window.setTimeout(() => setIsOpen(false), 150); }} onChange={(event) => { setQuery(event.target.value); setSelected(null); setIsOpen(true); onChange(null, null); }} placeholder={placeholder} disabled={disabled} className="block w-full rounded-md border border-slate-300 px-3 py-2 text-sm text-slate-900" /> {value && !disabled ? ( <button type="button" onClick={() => { setQuery(""); setSelected(null); setIsOpen(true); onChange(null, null); }} className="inline-flex h-10 w-10 items-center justify-center rounded-md border border-slate-300 text-slate-700" title="Clear HSN" > <X className="h-4 w-4" /> </button> ) : null} </div> {selected ? ( <div className="rounded-md border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-950"> <div className="font-medium"> {selected.code} - {selected.description} </div> <div>{selectedSummary}</div> </div> ) : null} {isOpen && !selected ? ( <div className="absolute z-30 max-h-72 w-full overflow-auto rounded-md border bg-white p-1 text-sm shadow-lg"> {isPending ? <div className="px-3 py-2 text-slate-500">Loading HSN codes...</div> : null} {!isPending && query.trim().length === 1 ? <div className="px-3 py-2 text-slate-500">Type at least 2 characters.</div> : null} {!isPending && query.trim().length !== 1 && results.length === 0 ? <div className="px-3 py-2 text-slate-500">No active HSN codes found.</div> : null} {results.map((item) => ( <button key={item.id} type="button" className="block w-full rounded px-3 py-2 text-left text-slate-900 hover:bg-slate-100" onMouseDown={(event) => event.preventDefault()} onClick={() => { setSelected(item); setQuery(`${item.code} - ${item.description}`); setIsOpen(false); onChange(item.id, item); }} > <div className="font-medium"> {item.code} — {item.description} — GST {String(item.gstRate)}% </div> <div className="text-xs text-slate-600"> GST: {String(item.gstRate)}% | CGST: {String(item.cgstRate)}% | SGST: {String(item.sgstRate)}% | IGST: {String(item.igstRate)}% </div> </button> ))} </div> ) : null} </div> );
}
