"use client";
import { Circle } from "lucide-react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import React from "react";
import { useForm } from "react-hook-form"; type PriceFilterProps = { slug?: string; isSearch?: boolean;
}; type PriceFormData = { min?: string; max?: string;
}; type PriceRange = { display: string; min?: number; max?: number;
};
export default function PriceFilter({ slug = "", isSearch }: PriceFilterProps) { const searchParams = useSearchParams(); const minParam = searchParams.get("min") || ""; const maxParam = searchParams.get("max") || ""; const searchTerm = searchParams.get("search") || ""; const subCategory = searchParams.get("subCategory") || ""; const sort = searchParams.get("sort") || "asc"; const page = Number.parseInt(searchParams.get("page") || "1", 10) || 1; const priceRanges: PriceRange[] = [ { display: "under 300", max: 300 }, { display: "Between 300 and 500", max: 500, min: 300 }, { display: "Between 500 and 700", max: 700, min: 500 }, { display: "Above 700", min: 700 }, ]; const router = useRouter(); const { handleSubmit, reset, register } = useForm<PriceFormData>(); function onSubmit(data: PriceFormData) { const min = data.min || ""; const max = data.max || ""; router.push( `/category/${slug}?page=${page}&sort=${sort}&min=${min}&max=${max}${ subCategory ? `&subCategory=${subCategory}` : "" }` ); reset(); } const hrefForRange = (range: PriceRange) => {
const params = new URLSearchParams({ page: String(page), sort, min: String(range.min ?? 0), max: String(range.max ?? ""), }); if (isSearch) params.set("search", searchTerm); if (subCategory) params.set("subCategory", subCategory); return `?${params.toString()}`; }; return ( <div className="liquid-card px-4 py-3"> <div className=""> <div className="flex justify-between items-center"> <h2 className="text-xl font-medium">Price </h2> <Link className="text-white bg-lime-700 hover:bg-lime-800 focus:ring-4 focus:ring-lime-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 focus:outline-none" href={ isSearch ? `/search?search=${searchTerm}` : `/category/${slug}${subCategory ? `?subCategory=${subCategory}` : ""}` } > Reset Filters </Link> </div> <div className="flex flex-col gap-3"> {priceRanges.map((range, i) => { const rangeMin = String(range.min ?? ""); const rangeMax = String(range.max ?? ""); const isActive = (!!range.min && rangeMin === minParam) || (!!range.max && rangeMax === maxParam) || (!!range.min && !!range.max && rangeMin === minParam && rangeMax === maxParam); return ( <Link key={i} href={hrefForRange(range)} className={isActive ? "flex gap-2 items-center text-lime-500" : "flex gap-2 items-center"} > <Circle className="w-4 h-4 flex-shrink-0" /> {range.display} </Link> ); })} </div> {isSearch ? null : ( <form onSubmit={handleSubmit(onSubmit)} className="grid grid-cols-3 gap-4 my-4"> <div className="col-span-1"> <input {...register("min")} type="number" id="min-price-input" aria-describedby="helper-text-explanation" className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-lime-500 focus:border-lime-500 block w-full p-2.5" placeholder="min" /> </div> <div className="col-span-1"> <input {...register("max")} type="number" id="max-price-input" aria-describedby="helper-text-explanation" className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-lime-500 focus:border-lime-500 block w-full p-2.5" placeholder="Max" /> </div> <div className="col-span-1"> <button type="submit" className="text-white bg-lime-700 hover:bg-lime-800 focus:ring-4 focus:ring-lime-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 focus:outline-none" > Go </button> </div> </form> )} </div> </div> );
}
