import db from "@/lib/db";
import { buildEnglishTranslationPayload, prismaUniqueMessage } from "@/lib/i18n/translationPayload";
import { safelyEnqueueTranslationJobs } from "@/lib/queues/safe-translation-enqueue";
import { createTranslationSourceHash } from "@/lib/translations/source-hash";
import { NextResponse } from "next/server"; const hsnCodeSelect = { id: true, code: true, description: true, gstRate: true, cgstRate: true, sgstRate: true, igstRate: true, cessRate: true, taxType: true, chapter: true, effectiveTo: true,
};
export async function GET(request: Request, context: { params: Promise<{ id: string }> }) { const { id } = await context.params; try { const category = await db.category.findUnique({ where: { id, }, include: { products: { include: { translations: true, variants: { where: { isActive: true }, include: { values: { include: { attribute: true, attributeValue: true, }, }, }, }, }, }, subCategories: { where: { isActive: true }, orderBy: [{ sortOrder: "asc" }, { title: "asc" }], include: { _count: { select: { products: true } }, translations: true, }, }, translations: true, hsnCode: { select: hsnCodeSelect, }, }, }); return NextResponse.json(category); } catch (error) { console.error(error); return NextResponse.json( { message: "Failed to Fetch Category", error, }, { status: 500 } ); } }
export async function DELETE(request: Request, context: { params: Promise<{ id: string }> }) { const { id } = await context.params; try { const existingCategory = await db.category.findUnique({ where: { id, }, include: { _count: { select: { products: true, subCategories: true } }, }, }); if (!existingCategory) { return NextResponse.json( { data: null, message: "Category Not Found", }, { status: 404 } ); } if ( existingCategory._count.products > 0 || existingCategory._count.subCategories > 0 ) { return NextResponse.json( { data: null, message: "Category cannot be deleted because it has linked subcategories, HSN mappings, or products.", }, { status: 400 } ); } const deletedCategory = await db.category.delete({ where: { id, }, }); return NextResponse.json(deletedCategory); } catch (error) { console.error(error); return NextResponse.json( { message: "Failed to Delete Category", error, }, { status: 500 } ); } }
export async function PUT(request: Request, context: { params: Promise<{ id: string }> }) { const { id } = await context.params; try { const { title, slug, imageUrl, description, hsnCodeId, isActive } = await request.json(); const englishTranslation = buildEnglishTranslationPayload({ title, slug, description, }); const sourceHash = createTranslationSourceHash(englishTranslation); const resolvedHsnCodeId = hsnCodeId || null; const hsnCode = resolvedHsnCodeId ? await db.hsnCode.findFirst({ where: { id: resolvedHsnCodeId, status: "ACTIVE", OR: [{ effectiveTo: null }, { effectiveTo: { gte: new Date() } }], }, select: { id: true }, }) : null; if (resolvedHsnCodeId && !hsnCode) { return NextResponse.json({ message: "Selected HSN code is invalid, inactive, or expired" }, { status: 400 }); } const existingCategory = await db.category.findUnique({ where: { id, }, }); if (!existingCategory) { return NextResponse.json( { data: null, message: `Not Found`, }, { status: 404 } ); } const updatedCategory = await db.$transaction(async (prisma) => {
const category = await prisma.category.update({ where: { id }, data: { title, slug, imageUrl, description, hsnCodeId: resolvedHsnCodeId, isActive }, }); await prisma.categoryTranslation.upsert({ where: { categoryId_language: { categoryId: id, language: englishTranslation.language, }, }, update: { title: englishTranslation.title, slug: englishTranslation.slug, description: englishTranslation.description, metaTitle: englishTranslation.metaTitle, metaDescription: englishTranslation.metaDescription, }, create: { categoryId: id, language: englishTranslation.language, title: englishTranslation.title, slug: englishTranslation.slug, description: englishTranslation.description, metaTitle: englishTranslation.metaTitle, metaDescription: englishTranslation.metaDescription, }, }); return prisma.category.findUnique({ where: { id: category.id }, include: { translations: true, hsnCode: { select: hsnCodeSelect, }, }, }); }); await safelyEnqueueTranslationJobs({ entityType: "CATEGORY", entityId: id, sourceHash, }); return NextResponse.json(updatedCategory); } catch (error) { console.error(error); return NextResponse.json( { message: prismaUniqueMessage(error, "Failed to Update Category"), error, }, { status: 500 } ); } } 