import { auth } from "@/auth";
import db from "@/lib/db";
import { safelyEnqueueTranslationJobs } from "@/lib/queues/safe-translation-enqueue";
import { createTranslationSourceHash } from "@/lib/translations/source-hash";
import { NextResponse } from "next/server";
import { assertAdmin } from "@/lib/security";
export async function GET(request: Request, context: { params: Promise<{ id: string }> }) { const { id } = await context.params; try { const training = await db.training.findUnique({ where: { id, }, include: { translations: true }, }); return NextResponse.json(training); } catch (error) { console.error(error); return NextResponse.json( { message: "Failed to Fetch Training", error, }, { status: 500 } ); }
}
export async function DELETE(request: Request, context: { params: Promise<{ id: string }> }) { const { id } = await context.params; try { const session = await auth(); const denied = assertAdmin(session); if (denied) return denied; const existingTraining = await db.training.findUnique({ where: { id, }, }); if (!existingTraining) { return NextResponse.json( { data: null, message: "Training Not Found", }, { status: 404 } ); } const deletedTraining = await db.training.delete({ where: { id, }, }); return NextResponse.json(deletedTraining); } catch (error) { console.error(error); return NextResponse.json( { message: "Failed to Delete Training", error, }, { status: 500 } ); }
}
export async function PUT(request: Request, context: { params: Promise<{ id: string }> }) { const { id } = await context.params; try { const session = await auth(); const denied = assertAdmin(session); if (denied) return denied; const { title, slug, categoryId, imageUrl, description, isActive, content, } = await request.json(); const sourceHash = createTranslationSourceHash({ title, slug, description, content, }); const existingTraining = await db.training.findUnique({ where: { id, }, include: { translations: { where: { language: "en" }, take: 1, }, }, }); if (!existingTraining) { return NextResponse.json( { data: null, message: `Not Found`, }, { status: 404 } ); } const updatedTraining = await db.$transaction(async (prisma) => {
const training = await prisma.training.update({ where: { id }, data: { title, slug, categoryId, imageUrl, description, isActive, content, }, }); await prisma.trainingTranslation.upsert({ where: { trainingId_language: { trainingId: id, language: "en" } }, update: { title, slug, description, content, }, create: { trainingId: id, language: "en", title, slug, description, content, }, }); return training; }); if (existingTraining.translations[0]?.sourceHash !== sourceHash) { await safelyEnqueueTranslationJobs({ entityType: "BLOG", entityId: id, sourceHash, }); } return NextResponse.json(updatedTraining); } catch (error) { console.error(error); return NextResponse.json( { message: "Failed to Update Training", error, }, { status: 500 } ); }
}
