import { auth } from "@/auth";
import db from "@/lib/db";
import { generateUserCode } from "@/lib/generateUserCode";
import bcrypt from "bcrypt";
import { NextResponse } from "next/server";
import { assertAdmin } from "@/lib/security"; const splitName = (name = "") => {
const parts = String(name).trim().split(/\s+/).filter(Boolean); return { firstName: parts[0] || "", lastName: parts.slice(1).join(" ") || "", };
};
const toNullableFloat = (value) => { if (value === "" || value === null || value === undefined) return null; const parsed = parseFloat(value); return Number.isFinite(parsed) ? parsed : null;
};
export async function POST(request) { try { const session = await auth(); const denied = assertAdmin(session); if (denied) return denied; /* code, contactPerson, contactPersonPhone, email, name, notes, phone, physicalAddress, terms, isActive, profileImageUrl, products, landSize, mainCrop, userId */ // Update the Verification in the user
const farmerData = await request.json(); const { firstName, lastName } = splitName(farmerData.name); const result = await db.$transaction(async (prisma) => { let farmerUser; if (farmerData.userId) { farmerUser = await prisma.user.findUnique({ where: { id: farmerData.userId }, }); if (!farmerUser) { throw new Error("No User Found"); } farmerUser = await prisma.user.update({ where: { id: farmerData.userId }, data: { name: farmerData.name || farmerUser.name, email: farmerData.email || farmerUser.email, emailVerified: true, role: "FARMER", status: farmerData.isActive ?? farmerUser.status, }, }); } else { if (!farmerData.name || !farmerData.email) { throw new Error("Farmer name and email are required"); } const existingUser = await prisma.user.findUnique({ where: { email: farmerData.email }, }); if (existingUser) { throw new Error(`User with this email (${farmerData.email}) already exists`); } const temporaryPassword = farmerData.password || farmerData.phone || `Farmer@${Date.now()}`; farmerUser = await prisma.user.create({ data: { name: farmerData.name, email: farmerData.email, password: await bcrypt.hash(temporaryPassword, 10), role: "FARMER", status: farmerData.isActive ?? true, emailVerified: true, }, }); } const existingProfile = await prisma.farmerProfile.findUnique({ where: { userId: farmerUser.id }, }); if (existingProfile) { throw new Error("Farmer profile already exists for this user"); } const code = farmerData.code || generateUserCode("LFF", farmerData.name || farmerUser.name || "Farmer"); const newFarmerProfile = await prisma.farmerProfile.create({ data: { code, contactPerson: farmerData.contactPerson || null, contactPersonPhone: farmerData.contactPersonPhone || null, profileImageUrl: farmerData.profileImageUrl || null, firstName, lastName, notes: farmerData.notes || null, phone: farmerData.phone || null, physicalAddress: farmerData.physicalAddress || null, terms: farmerData.terms || null, isActive: farmerData.isActive ?? true, products: farmerData.products || [], landSize: toNullableFloat(farmerData.landSize), mainCrop: farmerData.mainCrop || null, userId: farmerUser.id, }, }); return { user: farmerUser, farmerProfile: newFarmerProfile }; }); return NextResponse.json(result); } catch (error) { console.error(error); const message = error?.message || "Failed to create Farmer"; const status = message.includes("already exists") ? 409 : message === "No User Found" ? 404 : 500; return NextResponse.json( { message, error, }, { status } ); }
}
export async function GET(request) { try { const farmers = await db.user.findMany({ orderBy: { createdAt: "desc", }, where: { role: "FARMER", }, include: { farmerProfile: true, }, }); return NextResponse.json(farmers); } catch (error) { console.error(error); return NextResponse.json( { message: "Failed to Fetch FARMERs", error, }, { status: 500 } ); }
}
